[C95059561@bllintestboot3 Check_Users_Accounts]$ ansible-playbook -K -k -u fr-726-ansible -i inventaire-test.yml playbook-v2.yml
SSH password:
BECOME password[defaults to SSH password]:

PLAY [Audit sécurité utilisateurs (password policy, comptes inactifs, etc.)] **********************************************************************************************************************

TASK [Créer le répertoire temporaire sur l’hôte] **************************************************************************************************************************************************
ok: [bllinelk04]
ok: [bllintestboot]
ok: [bllinelk03]
ok: [bllinelk05]
ok: [artemis]
ok: [bllintestboot3]
ok: [bllina350rpm01]
ok: [buzet]
ok: [blnis01]
ok: [cfrc10353ap007]
ok: [cfrc10353ap009]
ok: [cfrc10353ap010]
ok: [cfrc10353ap011]

TASK [Copier le script d’audit sur l’hôte] ********************************************************************************************************************************************************
ok: [bllintestboot]
ok: [bllinelk04]
ok: [bllinelk03]
ok: [bllinelk05]
ok: [bllintestboot3]
ok: [artemis]
ok: [bllina350rpm01]
ok: [cfrc10353ap007]
ok: [cfrc10353ap009]
ok: [buzet]
ok: [cfrc10353ap010]
ok: [blnis01]
ok: [cfrc10353ap011]

TASK [Exécuter le script sur l’hôte distant] ******************************************************************************************************************************************************
changed: [bllinelk04]
changed: [bllintestboot]
changed: [bllinelk03]
changed: [bllinelk05]
changed: [bllintestboot3]
changed: [artemis]
changed: [bllina350rpm01]
changed: [blnis01]
changed: [cfrc10353ap007]
changed: [buzet]
changed: [cfrc10353ap009]
changed: [cfrc10353ap011]
changed: [cfrc10353ap010]

TASK [Créer le répertoire local pour les rapports de cet hôte] ************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/artemis'
fatal: [artemis -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.183851-3620222-85890160508015/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.183851-3620222-85890160508015/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.183851-3620222-85890160508015/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_m1wmb5mn/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_m1wmb5mn/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_m1wmb5mn/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_m1wmb5mn/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_m1wmb5mn/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/artemis'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk03'
fatal: [bllinelk03 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.1962123-3620223-122367970056855/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.1962123-3620223-122367970056855/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.1962123-3620223-122367970056855/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_43fwgubf/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_43fwgubf/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_43fwgubf/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_43fwgubf/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_43fwgubf/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk03'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk04'
fatal: [bllinelk04 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2144969-3620224-157587657612227/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2144969-3620224-157587657612227/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2144969-3620224-157587657612227/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_l2ghmk7a/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_l2ghmk7a/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_l2ghmk7a/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_l2ghmk7a/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_l2ghmk7a/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk04'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk05'
fatal: [bllinelk05 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2335536-3620226-249573092525800/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2335536-3620226-249573092525800/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2335536-3620226-249573092525800/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_bd5reonc/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_bd5reonc/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_bd5reonc/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_bd5reonc/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_bd5reonc/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllinelk05'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllintestboot'
fatal: [bllintestboot -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2449756-3620232-219223308343589/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2449756-3620232-219223308343589/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.2449756-3620232-219223308343589/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_ygcz1swe/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_ygcz1swe/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_ygcz1swe/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_ygcz1swe/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_ygcz1swe/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllintestboot'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllintestboot3'
fatal: [bllintestboot3 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8156247-3620303-244027919844842/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8156247-3620303-244027919844842/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8156247-3620303-244027919844842/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_n05ocds8/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_n05ocds8/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_n05ocds8/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_n05ocds8/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_n05ocds8/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllintestboot3'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/bllina350rpm01'
fatal: [bllina350rpm01 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8751607-3620314-16746013987098/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8751607-3620314-16746013987098/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.8751607-3620314-16746013987098/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_keprq6_1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_keprq6_1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_keprq6_1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_keprq6_1/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_keprq6_1/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/bllina350rpm01'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/blnis01'
fatal: [blnis01 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9235284-3620319-233733327641102/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9235284-3620319-233733327641102/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9235284-3620319-233733327641102/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_o21puvva/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_o21puvva/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_o21puvva/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_o21puvva/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_o21puvva/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/blnis01'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/buzet'
fatal: [buzet -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.941082-3620326-127140675259993/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.941082-3620326-127140675259993/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.941082-3620326-127140675259993/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_jhb_iylr/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_jhb_iylr/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_jhb_iylr/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_jhb_iylr/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_jhb_iylr/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/buzet'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap007'
fatal: [cfrc10353ap007 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9739673-3620343-246066893359586/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9739673-3620343-246066893359586/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931417.9739673-3620343-246066893359586/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_20tqf7e6/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_20tqf7e6/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_20tqf7e6/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_20tqf7e6/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_20tqf7e6/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap007'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap009'
fatal: [cfrc10353ap009 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.3678613-3620370-74492610220111/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.3678613-3620370-74492610220111/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.3678613-3620370-74492610220111/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_9azorows/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_9azorows/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_9azorows/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_9azorows/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_9azorows/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap009'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap011'
fatal: [cfrc10353ap011 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5225735-3620388-122848181298775/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5225735-3620388-122848181298775/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5225735-3620388-122848181298775/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_koiyqwdd/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_koiyqwdd/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_koiyqwdd/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_koiyqwdd/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_koiyqwdd/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap011'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: PermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap010'
fatal: [cfrc10353ap010 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5108855-3620385-88544452061813/AnsiballZ_file.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5108855-3620385-88544452061813/AnsiballZ_file.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/C95059561/.ansible/tmp/ansible-tmp-1750931418.5108855-3620385-88544452061813/AnsiballZ_file.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.file', init_globals=dict(_module_fqn='ansible.modules.file', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_i2vgzml1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 987, in <module>\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_i2vgzml1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 973, in main\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_i2vgzml1/ansible_ansible.builtin.file_payload.zip/ansible/modules/file.py\", line 680, in ensure_directory\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_i2vgzml1/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 1159, in set_fs_attributes_if_different\n  File \"/var/tmp/ansible_ansible.builtin.file_payload_i2vgzml1/ansible_ansible.builtin.file_payload.zip/ansible/module_utils/basic.py\", line 919, in set_mode_if_different\nPermissionError: [Errno 1] Opération non permise: b'./reports/cfrc10353ap010'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ****************************************************************************************************************************************************************************************
artemis                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllina350rpm01             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllinelk03                 : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllinelk04                 : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllinelk05                 : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllintestboot              : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
bllintestboot3             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
blnis01                    : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
buzet                      : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
cfrc10353ap007             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
cfrc10353ap009             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
cfrc10353ap010             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
cfrc10353ap011             : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[C95059561@bllintestboot3 Check_Users_Accounts]$
